### ISSUE TITLE
/dev/shm is mounted with noexec

### ISSUE THREAD

**Issue by kapsh** [zaufi/paludis-hooks#10]
Many of ebuilds fails with workdir-tmpfs because they trying to run something as ./build.sh or checking [[ -x ./configure ]] when /dev/shm is mounted with noexec (default option in most distros). 
I agree with this recommended option, so question is: how to have advantages of this beatiful hook without reducing security?

**Comment by zaufi** [comment]
huh, when you need smth to execute the underlaid filesystem definitely must be mounted w/ exec option enabled... so filesystem used by the hook must have this option anyway. there is some ways possible:
* improve the hook to support other locations (instead of hardcoded `/dev/shm`)
* mount other mountpoints, like `/tmp` (usually used by a web server as temporary upload location, thus concerned about security) w/ exec option turned off
* reconfigure concerned services to use other mount points (properly mounted)

**Comment by kapsh** [comment]
Ok, thank you, I've got it. Btw, are you using this hook without noexec in /dev/shm mount options?

**Comment by zaufi** [comment]
my options for tmpfs is here:

    none                        /dev/shm                  tmpfs       rw,relatime,size=10485760k
